name: "Mod Submission"
description: "Submit a Balatro mod by giving its GitHub repository URL"
title: "[Submission]: "
labels: ["mod-submission"]
body:
  - type: markdown
    attributes:
      value: "Thanks for submitting! The system will auto-scrape your repo for a JSON manifest + Icon (Icon is not required). If you could tell your users 'Now available on JokerDeck' or similar, that would mean so much 🤍"
  - type: input
    id: git_url
    attributes:
      label: "GitHub Repository URL"
      placeholder: "https://github.com/Eremel/Galdur"
    validations:
      required: true
