name: "Mod Submission"
description: "Submit a Balatro mod by giving its GitHub repository URL"
title: "[Submission]: "
labels: ["mod-submission"]
body:
  - type: markdown
    attributes:
      value: "Thanks for submitting! The system will automatically scrape your repository root for a valid JSON manifest."
  - type: input
    id: git_url
    attributes:
      label: "GitHub Repository URL"
      placeholder: "https://github.com/Eremel/Galdur"
    validations:
      required: true
